/* tslint:disable */
 
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SMS brand name information
 * @export
 * @interface BrandName
 */
export interface BrandName {
    /**
     * Brand identifier
     * @type {string}
     * @memberof BrandName
     */
    'id': string;
    /**
     * Brand name used as SMS sender
     * @type {string}
     * @memberof BrandName
     */
    'name': string;
    /**
     * Authorization status
     * @type {string}
     * @memberof BrandName
     */
    'authorized': string;
    /**
     * Brand creation timestamp
     * @type {string}
     * @memberof BrandName
     */
    'createdAt': string;
}

