/* tslint:disable */
/* eslint-disable */
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { BaseResponse } from './base-response';
// May contain unused imports in some cases
// @ts-ignore
import type { BrandName } from './brand-name';

/**
 * @type BrandNamesResponse
 * @export
 */
export type BrandNamesResponse = BaseResponse;


