/* tslint:disable */
 
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request payload for creating a brand name
 * @export
 * @interface CreateBrandNameRequest
 */
export interface CreateBrandNameRequest {
    /**
     * Brand name to create
     * @type {string}
     * @memberof CreateBrandNameRequest
     */
    'brandName': string;
}

