/* tslint:disable */
 
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * SMS delivery status for a phone number
 * @export
 * @interface DeliveryReportItem
 */
export interface DeliveryReportItem {
    /**
     * Phone number as string
     * @type {string}
     * @memberof DeliveryReportItem
     */
    'number': string;
    /**
     * Delivery status as string
     * @type {string}
     * @memberof DeliveryReportItem
     */
    'statusID': string;
}

