/* tslint:disable */
 
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.8
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Request payload for sending SMS
 * @export
 * @interface SendSMSRequest
 */
export interface SendSMSRequest {
    /**
     * Brand identifier as integer
     * @type {number}
     * @memberof SendSMSRequest
     */
    'brandID': number;
    /**
     * Array of phone numbers as integers
     * @type {Array<number>}
     * @memberof SendSMSRequest
     */
    'numbers': Array<number>;
    /**
     * SMS message text
     * @type {string}
     * @memberof SendSMSRequest
     */
    'text': string;
    /**
     * Enable/disable checking numbers in the stop list
     * @type {boolean}
     * @memberof SendSMSRequest
     */
    'stopList': boolean;
}

