/* tslint:disable */
/* eslint-disable */
/**
 * UBill API
 * UBill API - provides programmatic access to our resources. You will be able to integrate our service into your system and communicate with clients easily.
 *
 * The version of the OpenAPI document: 2.1.7
 * Contact: info@ubill.ge
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SMSPayload
 */
export interface SMSPayload {
    /**
     * 
     * @type {number}
     * @memberof SMSPayload
     */
    'brandID': number;
    /**
     * 
     * @type {Array<number>}
     * @memberof SMSPayload
     */
    'numbers': Array<number>;
    /**
     * 
     * @type {string}
     * @memberof SMSPayload
     */
    'text': string;
    /**
     * Enable/disable checking numbers in the stop list
     * @type {boolean}
     * @memberof SMSPayload
     */
    'stopList': boolean;
}

