name-template: 'ðŸš€ Generate v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-title-escapes: '\<*_&@#'
header: |
  ## ðŸ“‹ Changelog
category-template: '### $TITLE'
template: '$CHANGES'
change-template: '- $TITLE (#$NUMBER)'
footer: |

  ---
  **Full Changelog**: [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/ubill-ge/rd-test/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
autolabeler:
  - label: 'feature'
    title:
      - '/feat/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'refactor'
    title:
      - '/refactor/i'
  - label: 'docs'
    title:
      - '/docs/i'
  - label: 'dependencies'
    title:
      - '/chore\(deps\)/i'
categories:
  - title: 'âœ¨ Features'
    labels:
      - 'feature'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'bug'
  - title: 'â™»ï¸ Refactoring'
    labels:
      - 'refactor'
  - title: 'ðŸ“šï¸ Documentation'
    labels:
      - 'docs'
  - title: 'ðŸ“¦ Dependency Updates'
    labels:
      - 'dependencies'
  - title: 'ðŸ“ Other Changes'
    labels: [ ]
