name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  update-release-draft:
    uses: ubill-ge/sdk-generator/.github/workflows/sdk-release-drafter.yaml@main
    secrets: inherit
